-- Step 1: Add columns to existing resturant table
ALTER TABLE public.resturant
  ADD COLUMN IF NOT EXISTS restaurant_id TEXT,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS name_ja TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS area TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS address_ja TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS google_rating FLOAT,
  ADD COLUMN IF NOT EXISTS google_review_count INT,
  ADD COLUMN IF NOT EXISTS price_per_person_jpy INT,
  ADD COLUMN IF NOT EXISTS price_per_person_usd_approx INT,
  ADD COLUMN IF NOT EXISTS cuisine TEXT,
  ADD COLUMN IF NOT EXISTS michelin_stars INT,
  ADD COLUMN IF NOT EXISTS tabelog_score FLOAT,
  ADD COLUMN IF NOT EXISTS reservation_difficulty TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT;

-- Step 2: Insert all restaurants
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('tokyo_001', 'Sukiyabashi Jiro Honten', 'すきやばし次郎 本店', 'Tokyo', 'Ginza', '4-2-15 Ginza, Chuo City, Tokyo 104-0061', '東京都中央区銀座4-2-15 塚本素山ビルB1F', '+81-3-3535-3600', 4.2, 1180, 40000, 270, 'Sushi Omakase', 3, 4.7, 'Extremely Hard', 'Legendary sushi master Jiro Ono; reservation often requires hotel concierge');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('tokyo_002', 'Sushi Saito', '鮨さいとう', 'Tokyo', 'Minato (Mita)', '1-9-15 Mita, Minato City, Tokyo 108-0073', '東京都港区三田1-9-15', '+81-3-3455-0141', 4.5, 430, 55000, 370, 'Sushi Omakase', 3, 4.89, 'Extremely Hard', 'Consistently ranked #1 on Tabelog; nearly impossible without introduction');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('tokyo_003', 'Sushi Yoshitake', '鮨よしたけ', 'Tokyo', 'Ginza', '8-7-19 Ginza, Chuo City, Tokyo 104-0061', '東京都中央区銀座8-7-19 銀座ポケットビル3F', '+81-3-6253-7331', 4.5, 310, 60000, 400, 'Sushi Omakase', 3, 4.66, 'Very Hard', 'Refined Edomae sushi; elegant Ginza setting');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('tokyo_004', 'Sushi Sawada', '鮨さわだ', 'Tokyo', 'Ginza', '5-9-19 Ginza, Chuo City, Tokyo 104-0061', '東京都中央区銀座5-9-19 銀座MCビル3F', '+81-3-6215-7108', 4.5, 220, 55000, 370, 'Sushi Omakase', 3, 4.55, 'Very Hard', 'Masterful Edomae technique; intimate 8-seat counter');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('tokyo_005', 'Sushi Kanesaka', '鮨かねさか', 'Tokyo', 'Ginza', '8-10-3 Ginza, Chuo City, Tokyo 104-0061', '東京都中央区銀座8-10-3 東銀ビルB1F', '+81-3-5568-4411', 4.4, 500, 50000, 335, 'Sushi Omakase', 2, 4.4, 'Hard', 'Classic Edomae sushi; overseas reservations sometimes easier via concierge');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('tokyo_006', 'Hakkoku', 'はっこく', 'Tokyo', 'Ginza', '8-7-6 Ginza, Chuo City, Tokyo 104-0061', '東京都中央区銀座8-7-6 銀座コアビル3F', '+81-3-6280-6555', 4.6, 680, 38000, 255, 'Sushi Omakase', 1, 4.36, 'Hard', 'Popular with international guests; accepts online reservations via Tableall');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('tokyo_007', 'Sushi Harutaka', '鮨はるたか', 'Tokyo', 'Ginza', '8-5-8 Ginza, Chuo City, Tokyo 104-0061', '東京都中央区銀座8-5-8 デュープレックスギンザ 7F', '+81-3-6274-6580', 4.5, 390, 45000, 300, 'Sushi Omakase', 2, 4.48, 'Very Hard', 'Known for beautiful presentation and precise vinegar-rice balance');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('tokyo_008', 'Den', '傳', 'Tokyo', 'Jingumae (Harajuku)', '2-3-18 Jingumae, Shibuya City, Tokyo 150-0001', '東京都渋谷区神宮前2-3-18 Gidingビル1F', '+81-3-6434-4336', 4.6, 920, 32000, 215, 'Innovative Japanese (Omakase)', 2, 4.4, 'Hard', 'Playful, creative Japanese cuisine; chef Zaiyu Hasegawa; accepts foreign reservations online');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('tokyo_009', 'Narisawa', 'ナリサワ', 'Tokyo', 'Minami-Aoyama', '2-6-15 Minami-Aoyama, Minato City, Tokyo 107-0062', '東京都港区南青山2-6-15', '+81-3-5785-0799', 4.6, 1100, 42000, 280, 'Innovative Japanese', 2, 4.37, 'Moderate', 'Nature-inspired cuisine; sustainable focus; ranked in Asia''s 50 Best Restaurants');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('tokyo_010', 'Florilège', 'フロリレージュ', 'Tokyo', 'Minami-Aoyama', '2-5-4 Minami-Aoyama, Minato City, Tokyo 107-0062', '東京都港区南青山2-5-4 ゼロワン南青山B1F', '+81-3-6440-0878', 4.7, 760, 35000, 235, 'French-Japanese Omakase', 2, 4.38, 'Moderate', 'Chef Hiroyasu Kawate; open kitchen counter; globally acclaimed');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('tokyo_011', 'Ryugin', '龍吟', 'Tokyo', 'Roppongi', '7-17-24 Roppongi, Minato City, Tokyo 106-0032', '東京都港区六本木7-17-24 テレビ朝日通りビル1F', '+81-3-3423-8006', 4.6, 880, 38000, 255, 'Innovative Japanese (Kaiseki)', 3, 4.34, 'Hard', 'Chef Seiji Yamamoto; modern interpretation of washoku; seasonal ingredients');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('tokyo_012', 'L''Effervescence', 'レフェルヴェソンス', 'Tokyo', 'Nishi-Azabu', '2-26-4 Nishi-Azabu, Minato City, Tokyo 106-0031', '東京都港区西麻布2-26-4', '+81-3-5766-9500', 4.6, 650, 35000, 235, 'French-Japanese Omakase', 2, 4.33, 'Moderate', 'Chef Shinobu Namae; ethical sourcing; stunning seasonal menus');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('tokyo_013', 'Sushi Sho', '鮨 匠', 'Tokyo', 'Yotsuya', '6-3 Samon-cho, Shinjuku City, Tokyo 160-0017', '東京都新宿区左門町6-3', '+81-3-3355-5258', 4.4, 190, 45000, 300, 'Sushi Omakase', 1, 4.72, 'Extremely Hard', 'Chef Keiji Nakazawa; cult following; no phone reservations — introduction only');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('tokyo_014', 'Kagari Honten', 'かがり 本店', 'Tokyo', 'Ginza', '3-2-11 Ginza, Chuo City, Tokyo 104-0061', '東京都中央区銀座3-2-11', '+81-3-5524-8282', 4.3, 1450, 15000, 100, 'Ramen / Chicken broth', 1, 3.96, 'Queue', 'Michelin-starred ramen; walk-in queue; tori-paitan and shoyu options');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('kyoto_001', 'Kikunoi Honten', '菊乃井 本店', 'Kyoto', 'Higashiyama', '459 Shimokawara-cho, Higashiyama Ward, Kyoto 605-0825', '京都市東山区下河原町459', '+81-75-561-0015', 4.6, 1850, 35000, 235, 'Kaiseki', 3, 4.38, 'Moderate', 'Chef Murata''s flagship; accepts foreign reservations online; stunning garden setting');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('kyoto_002', 'Mizai', '未在', 'Kyoto', 'Fushimi', 'Fushimi Ward, Kyoto', '京都市伏見区', '+81-75-643-0231', 4.7, 290, 60000, 400, 'Kaiseki', 3, 4.85, 'Extremely Hard', 'Tabelog Kyoto #1; ultra-exclusive; introduction essentially required');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('kyoto_003', 'Hyotei', '瓢亭', 'Kyoto', 'Nanzenji', '35 Kusagawa-cho, Nanzenji, Sakyo Ward, Kyoto 606-8437', '京都市左京区南禅寺草川町35', '+81-75-771-4116', 4.5, 1020, 40000, 270, 'Kaiseki', 3, 4.53, 'Hard', '450-year history; famous soft-boiled egg; tranquil garden; also has a more casual annex');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('kyoto_004', 'Kichisen', '吉泉', 'Kyoto', 'Murasakino (Kita Ward)', '56-1 Kamigamo Misonoguchi-cho, Kita Ward, Kyoto 603-8072', '京都市北区上賀茂御薗口町56-1', '+81-75-711-0188', 4.7, 310, 80000, 535, 'Kaiseki', 3, 4.88, 'Extremely Hard', 'Among Japan''s most celebrated kaiseki; near Kamigamo Shrine; ultra-exclusive');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('kyoto_005', 'Nakamura', '中村楼', 'Kyoto', 'Gion', '508 Yasaka Shrine Torii-mae, Higashiyama Ward, Kyoto 605-0073', '京都市東山区祇園八坂神社鳥居前508', '+81-75-561-0016', 4.3, 780, 30000, 200, 'Kaiseki', 2, 4.17, 'Moderate', 'Over 460 years old; inside Yasaka Shrine precincts; historic atmosphere');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('kyoto_006', 'Yoshikawa', '吉川', 'Kyoto', 'Nakagyo Ward', 'Tominokoji, Oike-agaru, Nakagyo Ward, Kyoto 604-0832', '京都市中京区富小路通御池上る', '+81-75-221-5544', 4.5, 620, 25000, 168, 'Tempura Omakase', 1, 4.14, 'Moderate', 'Renowned tempura counter; also has inn (ryokan); excellent value for the quality');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('kyoto_007', 'Sushi Matsumoto', 'すし松本', 'Kyoto', 'Nakagyo Ward', 'Gojo Ohashi Nishi, Shimogyo Ward, Kyoto 600-8105', '京都市下京区五条大橋西詰', '+81-75-351-2413', 4.4, 480, 30000, 200, 'Sushi Omakase', 2, 4.32, 'Hard', 'Unique blend of Kyoto kaiseki sensibility with Edomae-style sushi');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('kyoto_008', 'Wa Yamamura', '和山村', 'Kyoto', 'Nakagyo Ward', 'Sakaimachi-dori Nijo, Nakagyo Ward, Kyoto 604-0931', '京都市中京区堺町通二条', '+81-75-257-5078', 4.5, 350, 28000, 188, 'Kaiseki', 1, 4.21, 'Moderate', 'Intimate 8-seat counter; seasonal Kyoto vegetables; good English support');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('kyoto_009', 'Shoraian', '松籟庵', 'Kyoto', 'Arashiyama', '34 Nakaoshima-cho, Arashiyama, Nishikyo Ward, Kyoto 616-0006', '京都市西京区嵐山中尾島町34', '+81-75-861-0123', 4.4, 720, 22000, 148, 'Kaiseki', 1, 4.1, 'Moderate', 'Riverside Arashiyama setting; bamboo grove views; scenic kaiseki experience');
INSERT INTO public.resturant (restaurant_id, name, name_ja, city, area, address, address_ja, phone, google_rating, google_review_count, price_per_person_jpy, price_per_person_usd_approx, cuisine, michelin_stars, tabelog_score, reservation_difficulty, notes) VALUES ('kyoto_010', 'Nishiki Warajiya', 'にしき わらじや', 'Kyoto', 'Nakagyo Ward (Nishiki)', 'Nishiki Market area, Nakagyo Ward, Kyoto', '京都市中京区錦市場周辺', '+81-75-221-0509', 4.3, 560, 18000, 121, 'Kaiseki / Obanzai', 1, 3.98, 'Easy', 'Approachable kaiseki near Nishiki Market; good for first-time kaiseki experience');
